import { Registration, CommunityUpdate, ForumDiscussion } from './types';

export const INITIAL_REGISTRATIONS: Registration[] = [
  {
    id: 'reg-1',
    communityId: 'GNC-2026-000101',
    fullName: 'Rajesh Namdev',
    fathersName: 'Karanlal Namdev',
    mothersName: 'Sushiladevi Namdev',
    gender: 'Male',
    dobOrAge: '34',
    mobileNumber: '9876543210',
    email: 'rajesh.namdev@gmail.com',
    gotra: 'Shandilya',
    education: 'B.Tech in Computer Science',
    occupation: 'Software Engineer',
    country: 'India',
    state: 'Madhya Pradesh',
    district: 'Indore',
    city: 'Indore',
    village: 'Palasia',
    relationship: 'Self',
    registrationDate: '2026-06-15',
    isVerified: true
  },
  {
    id: 'reg-2',
    communityId: 'GNC-2026-000102',
    fullName: 'Sneha Namdev',
    fathersName: 'Ramprasad Namdev',
    mothersName: 'Leeladevi Namdev',
    gender: 'Female',
    dobOrAge: '28',
    mobileNumber: '9123456789',
    email: 'sneha.n@yahoo.com',
    gotra: 'Kashyap',
    education: 'MBA in Finance',
    occupation: 'Financial Analyst',
    country: 'India',
    state: 'Maharashtra',
    district: 'Mumbai',
    city: 'Mumbai',
    village: '',
    relationship: 'Self',
    registrationDate: '2026-06-18',
    isVerified: true
  },
  {
    id: 'reg-3',
    communityId: 'GNC-2026-000103',
    fullName: 'Amit Kumar Namdev',
    fathersName: 'Gopal Krishna Namdev',
    mothersName: 'Kusum Namdev',
    gender: 'Male',
    dobOrAge: '42',
    mobileNumber: '9988776655',
    email: 'amit.namdev@outlook.com',
    gotra: 'Bharadwaj',
    education: 'MD Pediatrics',
    occupation: 'Doctor / Pediatrician',
    country: 'India',
    state: 'Gujarat',
    district: 'Ahmedabad',
    city: 'Ahmedabad',
    village: '',
    relationship: 'Self',
    registrationDate: '2026-06-20',
    isVerified: true
  },
  {
    id: 'reg-4',
    communityId: 'GNC-2026-000104',
    fullName: 'Vijay Namdev',
    fathersName: 'Babulal Namdev',
    mothersName: 'Savitri Namdev',
    gender: 'Male',
    dobOrAge: '55',
    mobileNumber: '9822114433',
    email: 'vijay.namdev@corporate.in',
    gotra: 'Vashistha',
    education: 'B.Com',
    occupation: 'Business Owner',
    country: 'India',
    state: 'Rajasthan',
    district: 'Jaipur',
    city: 'Jaipur',
    village: 'Sanganer',
    relationship: 'Self',
    registrationDate: '2026-06-22',
    isVerified: true
  },
  {
    id: 'reg-5',
    communityId: 'GNC-2026-000105',
    fullName: 'Vikram Namdev',
    fathersName: 'Devendra Namdev',
    mothersName: '',
    gender: 'Male',
    dobOrAge: '31',
    mobileNumber: '8877664433',
    email: 'v.namdev@gmail.com',
    gotra: 'Shandilya',
    education: 'M.S. in Data Science',
    occupation: 'Data Scientist',
    country: 'United States',
    state: 'California',
    district: 'Santa Clara',
    city: 'San Jose',
    village: '',
    relationship: 'Self',
    registrationDate: '2026-06-25',
    isVerified: true
  },
  {
    id: 'reg-6',
    communityId: 'GNC-2026-000106',
    fullName: 'Pooja Namdev',
    fathersName: 'Madanlal Namdev',
    mothersName: 'Geetadevi Namdev',
    gender: 'Female',
    dobOrAge: '24',
    mobileNumber: '9443322110',
    email: 'pooja.namdev@edu.in',
    gotra: 'Kashyap',
    education: 'B.Ed',
    occupation: 'School Teacher',
    country: 'India',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    city: 'Bhopal',
    village: '',
    relationship: 'Self',
    registrationDate: '2026-06-27',
    isVerified: true
  },
  {
    id: 'reg-7',
    communityId: 'GNC-2026-000107',
    fullName: 'Preeti Namdev',
    fathersName: 'Karanlal Namdev',
    mothersName: 'Sushiladevi Namdev',
    gender: 'Female',
    dobOrAge: '29',
    mobileNumber: '7766554433',
    email: 'preeti.n@gmail.com',
    gotra: 'Shandilya',
    education: 'M.Tech',
    occupation: 'Research Scientist',
    country: 'United Kingdom',
    state: 'Greater London',
    district: 'London Families',
    city: 'London',
    village: '',
    relationship: 'Sister',
    registrationDate: '2026-07-01',
    isVerified: true
  },
  {
    id: 'reg-8',
    communityId: 'GNC-2026-000108',
    fullName: 'Deepak Namdev',
    fathersName: 'Suresh Chandra Namdev',
    mothersName: 'Manjudevi Namdev',
    gender: 'Male',
    dobOrAge: '38',
    mobileNumber: '9001122334',
    email: 'deepak.namdev@gmail.com',
    gotra: 'Gautam',
    education: 'Diploma in Civil',
    occupation: 'Government Contractor',
    country: 'India',
    state: 'Madhya Pradesh',
    district: 'Ujjain',
    city: 'Ujjain',
    village: 'Nagda',
    relationship: 'Self',
    registrationDate: '2026-07-02',
    isVerified: true
  },
  {
    id: 'reg-9',
    communityId: 'GNC-2026-000109',
    fullName: 'Kiran Kumar Namdev',
    fathersName: 'Shivkumar Namdev',
    mothersName: 'Parvati Namdev',
    gender: 'Male',
    dobOrAge: '45',
    mobileNumber: '9845012345',
    email: 'kiran.k@namdev.org',
    gotra: 'Atri',
    education: 'B.Sc Agriculture',
    occupation: 'Agriculturist / Farmer',
    country: 'India',
    state: 'Maharashtra',
    district: 'Pune',
    city: 'Pune',
    village: 'Baramati',
    relationship: 'Self',
    registrationDate: '2026-07-04',
    isVerified: true
  },
  {
    id: 'reg-10',
    communityId: 'GNC-2026-000110',
    fullName: 'Hitesh Namdev',
    fathersName: 'Babulal Namdev',
    mothersName: 'Savitri Namdev',
    gender: 'Male',
    dobOrAge: '22',
    mobileNumber: '9654321098',
    email: 'hitesh.n@gmail.com',
    gotra: 'Vashistha',
    education: 'Undergraduate Student',
    occupation: 'Student',
    country: 'Canada',
    state: 'Ontario',
    district: 'Toronto Families',
    city: 'Toronto',
    village: '',
    relationship: 'Brother',
    registrationDate: '2026-07-05',
    isVerified: true
  },
  {
    id: 'reg-11',
    communityId: 'GNC-2026-000111',
    fullName: 'Arun Namdev',
    fathersName: 'Manohar Namdev',
    mothersName: 'Sushmadevi Namdev',
    gender: 'Male',
    dobOrAge: '33',
    mobileNumber: '9545009988',
    email: 'arun.namdev@gmail.com',
    gotra: 'Shandilya',
    education: 'B.Design',
    occupation: 'Fashion Designer',
    country: 'Australia',
    state: 'New South Wales',
    district: 'Sydney Hub',
    city: 'Sydney',
    village: '',
    relationship: 'Self',
    registrationDate: '2026-07-06',
    isVerified: true
  },
  {
    id: 'reg-12',
    communityId: 'GNC-2026-000112',
    fullName: 'Manoj Namdev',
    fathersName: 'Radheshyam Namdev',
    mothersName: 'Anitadevi Namdev',
    gender: 'Male',
    dobOrAge: '49',
    mobileNumber: '9893011223',
    email: 'manoj.namdev@bhopal.in',
    gotra: 'Bharadwaj',
    education: 'M.Com',
    occupation: 'Chartered Accountant',
    country: 'India',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    city: 'Bhopal',
    village: '',
    relationship: 'Self',
    registrationDate: '2026-07-08',
    isVerified: true
  }
];

export const INITIAL_UPDATES: CommunityUpdate[] = [
  {
    id: 'up-1',
    category: 'scholarship',
    title: 'GNC Merit Scholarship Scheme 2026 Announced',
    message: 'We are proud to announce the GNC annual scholarship for young Namdev students pursuing engineering, medical, or research studies. Applications are open to all registered community members worldwide with a GPA of 3.8/4 or equivalent.',
    time: 'July 09, 2026',
    isRead: true,
  },
  {
    id: 'up-2',
    category: 'blood-camp',
    title: 'Mega Blood Donation Drive: Maharashtra Families',
    message: 'Coordinated by Namdev Yuva Federation in Pune and Mumbai on July 19th. Register online to volunteer or donate. All participants will receive an appreciation certificate and a GNC community badge.',
    time: 'July 08, 2026',
    isRead: true,
  },
  {
    id: 'up-3',
    category: 'announcement',
    title: 'Digital Directory Growing Across Countries',
    message: 'Our member directory is expanding with registrations from multiple countries. We urge every family head to register their members to complete the digital directory and establish stronger professional networks.',
    time: 'July 05, 2026',
    isRead: true,
  },
  {
    id: 'up-4',
    category: 'festival',
    title: 'Ashadi Ekadashi Namdev Bhajan Festival Greetings',
    message: 'Wishing Namdev family members a peaceful and spiritual Ashadi Ekadashi. This day is incredibly significant to our heritage, remembering Sant Namdev Maharaj\'s devotion.',
    time: 'July 03, 2026',
    isRead: true,
  },
  {
    id: 'up-5',
    category: 'meeting',
    title: 'Global Career Mentorship Connect - Virtual Meetup',
    message: 'An interactive virtual webinar where community leaders and entrepreneurs from the US, Australia, and the UK will mentor young graduates from across the world.',
    time: 'June 28, 2026',
    isRead: true,
  },
  {
    id: 'up-6',
    category: 'announcement',
    title: 'Community ID Cards Now Available for Download',
    message: 'Registered members can download their verified digital ID from the Community ID section.',
    time: 'June 25, 2026',
    isRead: true,
    imageUrl: 'https://picsum.photos/seed/gnc-up-6/800/480',
  },
  {
    id: 'up-7',
    category: 'scholarship',
    title: 'Regional Science Fair — Student Project Grants',
    message: 'Short-term grants for Namdev youth presenting research at state and national science fairs.\n\nEligibility:\n- Age 14–22\n- Registered GNC member\n- Project abstract required\n\nApply before August 01, 2026 at https://example.com/science-grant',
    time: 'June 22, 2026',
    isRead: true,
  },
  {
    id: 'up-8',
    category: 'event',
    title: 'Delhi NCR Family Meetup — Save the Date',
    message: 'Annual gathering for Namdev families in Delhi NCR. Venue and RSVP details coming soon.',
    time: 'June 20, 2026',
    isRead: true,
    imageUrl: 'https://picsum.photos/seed/gnc-up-8/800/480',
  },
  {
    id: 'up-9',
    category: 'blood-camp',
    title: 'Hyderabad Blood Donation Camp — July 26',
    message: 'Join the Hyderabad chapter for a community blood donation drive.\n\nVenue: Community Hall, Secunderabad\nTime: 9:00 AM – 4:00 PM\n\nWalk-in donors welcome. Carry a valid photo ID.',
    time: 'June 18, 2026',
    isRead: true,
  },
  {
    id: 'up-10',
    category: 'festival',
    title: 'Guru Purnima Greetings to All Members',
    message: 'Warm wishes on Guru Purnima from the Global Namdev Community team.',
    time: 'June 15, 2026',
    isRead: true,
  },
  {
    id: 'up-11',
    category: 'meeting',
    title: 'Women Entrepreneurs Roundtable — Online Session',
    message: 'An open forum for Namdev women running businesses or startups to share experiences, challenges, and mentorship opportunities.\n\nAgenda:\n1. Welcome and introductions\n2. Panel: scaling local businesses\n3. Open Q&A\n\nRegister: https://example.com/women-roundtable',
    time: 'June 12, 2026',
    isRead: true,
    imageUrl: 'https://picsum.photos/seed/gnc-up-11/800/480',
  },
  {
    id: 'up-12',
    category: 'announcement',
    title: 'Portal Maintenance Window — July 12 Night',
    message: 'Brief scheduled maintenance from 11:30 PM to 1:00 AM IST. Registration and login may be unavailable.',
    time: 'June 10, 2026',
    isRead: true,
  },
  {
    id: 'up-13',
    category: 'scholarship',
    title: 'UK Chapter — Undergraduate Support Fund',
    message: 'Financial assistance for Namdev students starting university in the United Kingdom this autumn.',
    time: 'June 08, 2026',
    isRead: true,
  },
  {
    id: 'up-14',
    category: 'blood-camp',
    title: 'Bengaluru Community Blood Drive — August 2',
    message: 'Volunteer donors needed for the annual Bengaluru blood donation camp.\n\nLocation: Whitefield Community Center\nHours: 8:00 AM – 3:00 PM',
    time: 'June 06, 2026',
    isRead: true,
    imageUrl: 'https://picsum.photos/seed/gnc-up-14/800/480',
  },
  {
    id: 'up-15',
    category: 'meeting',
    title: 'Youth Leadership Forum — Monthly Call',
    message: 'Open Zoom session for members aged 18–30 to discuss volunteering, careers, and chapter activities.',
    time: 'June 04, 2026',
    isRead: true,
  },
  {
    id: 'up-16',
    category: 'festival',
    title: 'Diwali Community Greetings 2026',
    message: 'Wishing every Namdev household joy, prosperity, and togetherness this Diwali season.',
    time: 'June 02, 2026',
    isRead: true,
  },
  {
    id: 'up-17',
    category: 'event',
    title: 'Pune Heritage Walk — Sant Namdev Trail',
    message: 'Guided heritage walk covering key sites linked to Sant Namdev Maharaj in Pune city.\n\nDate: August 10, 2026\nMeeting point: Mandir gate, 7:00 AM\n\nRegister early — limited slots.',
    time: 'May 30, 2026',
    isRead: true,
    imageUrl: 'https://picsum.photos/seed/gnc-up-17/800/480',
  },
  {
    id: 'up-18',
    category: 'announcement',
    title: 'New Volunteer Coordinators Appointed',
    message: 'State volunteer leads announced for Maharashtra, Karnataka, and Gujarat chapters.',
    time: 'May 28, 2026',
    isRead: true,
  },
  {
    id: 'up-19',
    category: 'scholarship',
    title: 'Medical Entrance Coaching Subsidy — 2026 Batch',
    message: 'Partial fee support for registered students enrolled in NEET or equivalent medical entrance coaching programs.\n\nDocuments required:\n- Coaching enrollment proof\n- Community ID\n- Parent/guardian contact',
    time: 'May 26, 2026',
    isRead: true,
  },
  {
    id: 'up-20',
    category: 'blood-camp',
    title: 'Chennai Platelet Donation Awareness Week',
    message: 'Awareness campaign on platelet donation with partner hospitals across Chennai.',
    time: 'May 24, 2026',
    isRead: true,
  },
  {
    id: 'up-21',
    category: 'meeting',
    title: 'Canada Chapter — Virtual Town Hall',
    message: 'Monthly town hall for members in Canada to share updates on local events and membership drives.',
    time: 'May 22, 2026',
    isRead: true,
    imageUrl: 'https://picsum.photos/seed/gnc-up-21/800/480',
  },
  {
    id: 'up-22',
    category: 'festival',
    title: 'Gudi Padwa Wishes — Maharashtra Members',
    message: 'Happy Gudi Padwa to all Namdev families celebrating across Maharashtra and beyond.',
    time: 'May 20, 2026',
    isRead: true,
  },
  {
    id: 'up-23',
    category: 'event',
    title: 'Indore Sports Day for Community Youth',
    message: 'Annual sports day with cricket, kabaddi, and athletics for members under 25.\n\nVenue: Indore Sports Complex\nDate: September 5, 2026',
    time: 'May 18, 2026',
    isRead: true,
  },
  {
    id: 'up-24',
    category: 'announcement',
    title: 'Forum Guidelines Updated',
    message: 'Please review the updated community forum guidelines before posting new discussions.',
    time: 'May 16, 2026',
    isRead: true,
    imageUrl: 'https://picsum.photos/seed/gnc-up-24/800/480',
  },
  {
    id: 'up-25',
    category: 'scholarship',
    title: 'Girls in STEM Scholarship — Applications Open',
    message: 'Encouraging Namdev girls pursuing science, technology, engineering, and mathematics courses at college level.',
    time: 'May 14, 2026',
    isRead: true,
  },
  {
    id: 'up-26',
    category: 'blood-camp',
    title: 'Nagpur Emergency Blood Registry Drive',
    message: 'Register as a voluntary blood donor for the Nagpur emergency response network.\n\nBring ID and recent health summary if available.',
    time: 'May 12, 2026',
    isRead: true,
  },
  {
    id: 'up-27',
    category: 'meeting',
    title: 'Australia Chapter — Career Networking Evening',
    message: 'In-person networking for professionals in Sydney and Melbourne. Short talks, mentorship sign-ups, and dinner.\n\nRSVP required by July 20, 2026.',
    time: 'May 10, 2026',
    isRead: true,
    imageUrl: 'https://picsum.photos/seed/gnc-up-27/800/480',
  },
];

/** Merge any new seed bulletins into saved local data (for demo / seed updates). */
export function loadCommunityUpdates(): CommunityUpdate[] {
  const seedIds = new Set(INITIAL_UPDATES.map((update) => update.id));

  try {
    const saved = localStorage.getItem('gnc_updates');
    if (!saved) {
      return INITIAL_UPDATES.map((update) => ({
        ...update,
        isRead: update.isRead ?? seedIds.has(update.id),
      }));
    }

    const stored: CommunityUpdate[] = JSON.parse(saved);
    const storedIds = new Set(stored.map((update) => update.id));
    const missingSeeds = INITIAL_UPDATES.filter((update) => !storedIds.has(update.id));

    const merged = [...stored, ...missingSeeds];
    return merged.map((update) => ({
      ...update,
      isRead: update.isRead ?? seedIds.has(update.id),
    }));
  } catch {
    return INITIAL_UPDATES;
  }
}

export const INITIAL_DISCUSSIONS: ForumDiscussion[] = [
  {
    id: 'disc-1',
    author: 'Rajesh Namdev',
    authorRole: 'Software Engineer',
    title: 'Welcome to the Global Namdev Community Portal!',
    content: 'Namaskar members! Welcome to our new digital member directory portal. Please share your feedback and register your family members to build our global connection stronger.',
    time: '2 hours ago',
    category: 'General',
    likes: 12,
    replies: [
      { id: 'c-1', author: 'Sneha Namdev', text: 'This is amazing! Extremely clean and modern. Great effort!', time: '1 hour ago' }
    ]
  },
  {
    id: 'disc-2',
    author: 'Amit Kumar Namdev',
    authorRole: 'Pediatrician',
    title: 'Coordinating Blood Camps & Youth Healthcare Forums',
    content: 'We are planning to organize free online wellness sessions for kids and regional blood drives. Please comment if you would like to volunteer in your respective state family networks.',
    time: '1 day ago',
    category: 'Health',
    likes: 8,
    replies: []
  }
];

