import { Registration, CommunityUpdate, ForumDiscussion } from './types';

export const INITIAL_REGISTRATIONS: Registration[] = [
  {
    id: 'reg-1',
    communityId: 'GNC-2026-000101',
    fullName: 'Rajesh Namdev',
    fathersName: 'Karanlal Namdev',
    mothersName: 'Sushiladevi Namdev',
    gender: 'Male',
    dobOrAge: '34',
    mobileNumber: '9876543210',
    email: 'rajesh.namdev@gmail.com',
    gotra: 'Shandilya',
    education: 'B.Tech in Computer Science',
    occupation: 'Software Engineer',
    country: 'India',
    state: 'Madhya Pradesh',
    district: 'Indore',
    city: 'Indore',
    village: 'Palasia',
    relationship: 'Self',
    registrationDate: '2026-06-15',
    isVerified: true
  },
  {
    id: 'reg-2',
    communityId: 'GNC-2026-000102',
    fullName: 'Sneha Namdev',
    fathersName: 'Ramprasad Namdev',
    mothersName: 'Leeladevi Namdev',
    gender: 'Female',
    dobOrAge: '28',
    mobileNumber: '9123456789',
    email: 'sneha.n@yahoo.com',
    gotra: 'Kashyap',
    education: 'MBA in Finance',
    occupation: 'Financial Analyst',
    country: 'India',
    state: 'Maharashtra',
    district: 'Mumbai',
    city: 'Mumbai',
    village: '',
    relationship: 'Self',
    registrationDate: '2026-06-18',
    isVerified: true
  },
  {
    id: 'reg-3',
    communityId: 'GNC-2026-000103',
    fullName: 'Amit Kumar Namdev',
    fathersName: 'Gopal Krishna Namdev',
    mothersName: 'Kusum Namdev',
    gender: 'Male',
    dobOrAge: '42',
    mobileNumber: '9988776655',
    email: 'amit.namdev@outlook.com',
    gotra: 'Bharadwaj',
    education: 'MD Pediatrics',
    occupation: 'Doctor / Pediatrician',
    country: 'India',
    state: 'Gujarat',
    district: 'Ahmedabad',
    city: 'Ahmedabad',
    village: '',
    relationship: 'Self',
    registrationDate: '2026-06-20',
    isVerified: true
  },
  {
    id: 'reg-4',
    communityId: 'GNC-2026-000104',
    fullName: 'Vijay Namdev',
    fathersName: 'Babulal Namdev',
    mothersName: 'Savitri Namdev',
    gender: 'Male',
    dobOrAge: '55',
    mobileNumber: '9822114433',
    email: 'vijay.namdev@corporate.in',
    gotra: 'Vashistha',
    education: 'B.Com',
    occupation: 'Business Owner',
    country: 'India',
    state: 'Rajasthan',
    district: 'Jaipur',
    city: 'Jaipur',
    village: 'Sanganer',
    relationship: 'Self',
    registrationDate: '2026-06-22',
    isVerified: true
  },
  {
    id: 'reg-5',
    communityId: 'GNC-2026-000105',
    fullName: 'Vikram Namdev',
    fathersName: 'Devendra Namdev',
    mothersName: '',
    gender: 'Male',
    dobOrAge: '31',
    mobileNumber: '8877664433',
    email: 'v.namdev@gmail.com',
    gotra: 'Shandilya',
    education: 'M.S. in Data Science',
    occupation: 'Data Scientist',
    country: 'United States',
    state: 'California',
    district: 'Santa Clara',
    city: 'San Jose',
    village: '',
    relationship: 'Self',
    registrationDate: '2026-06-25',
    isVerified: true
  },
  {
    id: 'reg-6',
    communityId: 'GNC-2026-000106',
    fullName: 'Pooja Namdev',
    fathersName: 'Madanlal Namdev',
    mothersName: 'Geetadevi Namdev',
    gender: 'Female',
    dobOrAge: '24',
    mobileNumber: '9443322110',
    email: 'pooja.namdev@edu.in',
    gotra: 'Kashyap',
    education: 'B.Ed',
    occupation: 'School Teacher',
    country: 'India',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    city: 'Bhopal',
    village: '',
    relationship: 'Self',
    registrationDate: '2026-06-27',
    isVerified: true
  },
  {
    id: 'reg-7',
    communityId: 'GNC-2026-000107',
    fullName: 'Preeti Namdev',
    fathersName: 'Karanlal Namdev',
    mothersName: 'Sushiladevi Namdev',
    gender: 'Female',
    dobOrAge: '29',
    mobileNumber: '7766554433',
    email: 'preeti.n@gmail.com',
    gotra: 'Shandilya',
    education: 'M.Tech',
    occupation: 'Research Scientist',
    country: 'United Kingdom',
    state: 'Greater London',
    district: 'London Families',
    city: 'London',
    village: '',
    relationship: 'Sister',
    registrationDate: '2026-07-01',
    isVerified: true
  },
  {
    id: 'reg-8',
    communityId: 'GNC-2026-000108',
    fullName: 'Deepak Namdev',
    fathersName: 'Suresh Chandra Namdev',
    mothersName: 'Manjudevi Namdev',
    gender: 'Male',
    dobOrAge: '38',
    mobileNumber: '9001122334',
    email: 'deepak.namdev@gmail.com',
    gotra: 'Gautam',
    education: 'Diploma in Civil',
    occupation: 'Government Contractor',
    country: 'India',
    state: 'Madhya Pradesh',
    district: 'Ujjain',
    city: 'Ujjain',
    village: 'Nagda',
    relationship: 'Self',
    registrationDate: '2026-07-02',
    isVerified: true
  },
  {
    id: 'reg-9',
    communityId: 'GNC-2026-000109',
    fullName: 'Kiran Kumar Namdev',
    fathersName: 'Shivkumar Namdev',
    mothersName: 'Parvati Namdev',
    gender: 'Male',
    dobOrAge: '45',
    mobileNumber: '9845012345',
    email: 'kiran.k@namdev.org',
    gotra: 'Atri',
    education: 'B.Sc Agriculture',
    occupation: 'Agriculturist / Farmer',
    country: 'India',
    state: 'Maharashtra',
    district: 'Pune',
    city: 'Pune',
    village: 'Baramati',
    relationship: 'Self',
    registrationDate: '2026-07-04',
    isVerified: true
  },
  {
    id: 'reg-10',
    communityId: 'GNC-2026-000110',
    fullName: 'Hitesh Namdev',
    fathersName: 'Babulal Namdev',
    mothersName: 'Savitri Namdev',
    gender: 'Male',
    dobOrAge: '22',
    mobileNumber: '9654321098',
    email: 'hitesh.n@gmail.com',
    gotra: 'Vashistha',
    education: 'Undergraduate Student',
    occupation: 'Student',
    country: 'Canada',
    state: 'Ontario',
    district: 'Toronto Families',
    city: 'Toronto',
    village: '',
    relationship: 'Brother',
    registrationDate: '2026-07-05',
    isVerified: true
  },
  {
    id: 'reg-11',
    communityId: 'GNC-2026-000111',
    fullName: 'Arun Namdev',
    fathersName: 'Manohar Namdev',
    mothersName: 'Sushmadevi Namdev',
    gender: 'Male',
    dobOrAge: '33',
    mobileNumber: '9545009988',
    email: 'arun.namdev@gmail.com',
    gotra: 'Shandilya',
    education: 'B.Design',
    occupation: 'Fashion Designer',
    country: 'Australia',
    state: 'New South Wales',
    district: 'Sydney Hub',
    city: 'Sydney',
    village: '',
    relationship: 'Self',
    registrationDate: '2026-07-06',
    isVerified: true
  },
  {
    id: 'reg-12',
    communityId: 'GNC-2026-000112',
    fullName: 'Manoj Namdev',
    fathersName: 'Radheshyam Namdev',
    mothersName: 'Anitadevi Namdev',
    gender: 'Male',
    dobOrAge: '49',
    mobileNumber: '9893011223',
    email: 'manoj.namdev@bhopal.in',
    gotra: 'Bharadwaj',
    education: 'M.Com',
    occupation: 'Chartered Accountant',
    country: 'India',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    city: 'Bhopal',
    village: '',
    relationship: 'Self',
    registrationDate: '2026-07-08',
    isVerified: true
  }
];

/** Load bulletins from local storage (demo mode without Supabase). */
export function loadCommunityUpdates(): CommunityUpdate[] {
  try {
    const saved = localStorage.getItem('gnc_updates');
    return saved ? (JSON.parse(saved) as CommunityUpdate[]) : [];
  } catch {
    return [];
  }
}

export const INITIAL_DISCUSSIONS: ForumDiscussion[] = [
  {
    id: 'disc-1',
    author: 'Rajesh Namdev',
    authorRole: 'Software Engineer',
    title: 'Welcome to the Global Namdev Community Portal!',
    content: 'Namaskar members! Welcome to our new digital member directory portal. Please share your feedback and register your family members to build our global connection stronger.',
    time: '2 hours ago',
    category: 'General',
    likes: 12,
    replies: [
      { id: 'c-1', author: 'Sneha Namdev', text: 'This is amazing! Extremely clean and modern. Great effort!', time: '1 hour ago' }
    ]
  },
  {
    id: 'disc-2',
    author: 'Amit Kumar Namdev',
    authorRole: 'Pediatrician',
    title: 'Coordinating Blood Camps & Youth Healthcare Forums',
    content: 'We are planning to organize free online wellness sessions for kids and regional blood drives. Please comment if you would like to volunteer in your respective state family networks.',
    time: '1 day ago',
    category: 'Health',
    likes: 8,
    replies: []
  }
];

